import { Organization } from './types';

export const dummyOrganizations: Organization[] = [
  {
    id: '1',
    title: 'Ministry of Technology',
    type: 'Ministry',
    description: 'Leading the technological innovation on campus through workshops, hackathons, and development projects.',
    fullDescription: 'The Ministry of Technology is the premier tech organization on campus, dedicated to fostering innovation and technical excellence. We organize regular hackathons, workshops on cutting-edge technologies, and collaborative projects that push the boundaries of what students can achieve. Our members work on real-world applications, contribute to open-source projects, and build solutions that impact the campus community.',
    imageUrl: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Technology', 'Innovation', 'Development'],
    inductionsOpen: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Ashoka Business Club',
    type: 'Club',
    description: 'Empowering future business leaders through case competitions, networking events, and industry interactions.',
    fullDescription: 'Ashoka Business Club is dedicated to developing the business acumen of students through practical exposure to real-world business challenges. We host case competitions, invite industry leaders for talks, organize networking sessions with alumni, and provide mentorship opportunities. Our members gain insights into various business domains including consulting, finance, marketing, and entrepreneurship.',
    imageUrl: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Business', 'Entrepreneurship', 'Finance'],
    inductionsOpen: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '3',
    title: 'Ashoka Debating Union',
    type: 'Club',
    description: 'Fostering critical thinking and public speaking through competitive debates and parliamentary discussions.',
    fullDescription: 'The Ashoka Debating Union has a rich tradition of excellence in competitive debating. We train members in various debate formats including British Parliamentary, Asian Parliamentary, and World Schools. Our members regularly compete at national and international tournaments, bringing home accolades. Beyond competition, we focus on developing critical thinking, research skills, and articulate expression.',
    imageUrl: 'https://images.pexels.com/photos/3184436/pexels-photo-3184436.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Debate', 'Public Speaking', 'Critical Thinking'],
    inductionsOpen: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '4',
    title: 'Anime Club',
    type: 'Club',
    description: 'Celebrating Japanese animation and culture through screenings, discussions, and cultural events.',
    fullDescription: 'The Anime Club is a vibrant community for enthusiasts of Japanese animation and culture. We organize weekly screenings of popular and classic anime series, host discussion sessions on themes and storytelling techniques, celebrate Japanese festivals, and occasionally coordinate trips to anime conventions. Members share recommendations, create fan content, and explore the artistic and cultural dimensions of anime.',
    imageUrl: 'https://images.pexels.com/photos/3255761/pexels-photo-3255761.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Culture', 'Entertainment', 'Media'],
    inductionsOpen: false,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '5',
    title: 'Ashoka Consulting Club',
    type: 'Club',
    description: 'Preparing students for consulting careers through case practice, workshops, and industry projects.',
    fullDescription: 'Ashoka Consulting Club prepares students for careers in management consulting through rigorous case practice, workshops on consulting frameworks, and live projects with organizations. We conduct boot camps before recruitment seasons, organize networking events with consulting firms, and provide peer mentorship. Our alumni work at top consulting firms globally and regularly engage with current members.',
    imageUrl: 'https://images.pexels.com/photos/3184357/pexels-photo-3184357.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Consulting', 'Strategy', 'Business'],
    inductionsOpen: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '6',
    title: 'Photography Society',
    type: 'Society',
    description: 'Capturing moments and telling stories through the lens, from campus events to artistic exhibitions.',
    fullDescription: 'The Photography Society is committed to the art and craft of photography. We conduct workshops on technical skills, organize photo walks around campus and the city, host exhibitions showcasing member work, and cover campus events. Members learn various photography styles including portrait, landscape, street, and documentary photography. We also provide equipment and editing resources to members.',
    imageUrl: 'https://images.pexels.com/photos/3225531/pexels-photo-3225531.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Arts', 'Visual Media', 'Documentation'],
    inductionsOpen: false,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '7',
    title: 'Dance Society',
    type: 'Society',
    description: 'Expressing creativity through diverse dance forms, from contemporary to classical and everything in between.',
    fullDescription: 'Our Dance Society celebrates movement and expression through various dance forms. We offer regular workshops in contemporary, hip-hop, classical Indian dance forms, and fusion styles. Members choreograph pieces for campus performances, compete at inter-college festivals, and collaborate with other arts organizations. The society provides a supportive environment for dancers of all skill levels to grow and perform.',
    imageUrl: 'https://images.pexels.com/photos/3646104/pexels-photo-3646104.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Performing Arts', 'Dance', 'Culture'],
    inductionsOpen: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '8',
    title: 'Environmental Club',
    type: 'Club',
    description: 'Promoting sustainability and environmental awareness through campus initiatives and community projects.',
    fullDescription: 'The Environmental Club works towards making the campus and surrounding community more sustainable. We organize tree plantation drives, waste management workshops, awareness campaigns on climate change, and collaborate with local NGOs on environmental projects. Members research sustainable practices, advocate for policy changes, and implement green initiatives on campus.',
    imageUrl: 'https://images.pexels.com/photos/3255761/pexels-photo-3255761.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Environment', 'Sustainability', 'Social Impact'],
    inductionsOpen: false,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '9',
    title: 'Literary Society',
    type: 'Society',
    description: 'Nurturing writers and readers through poetry slams, book clubs, and creative writing workshops.',
    fullDescription: 'The Literary Society is a haven for lovers of the written word. We host regular open mic nights, organize book clubs discussing contemporary and classic literature, conduct creative writing workshops, and publish an annual literary magazine featuring student work. Members explore various forms of writing including poetry, short fiction, essays, and experimental prose.',
    imageUrl: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Literature', 'Creative Writing', 'Arts'],
    inductionsOpen: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '10',
    title: 'Robotics Department',
    type: 'Department',
    description: 'Building the future with autonomous systems, AI integration, and innovative robotics solutions.',
    fullDescription: 'The Robotics Department combines hardware and software to create intelligent autonomous systems. We participate in national and international robotics competitions, conduct research on machine learning applications in robotics, and build projects ranging from line-following robots to advanced AI-powered systems. Members learn embedded programming, mechanical design, and system integration.',
    imageUrl: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Robotics', 'AI', 'Engineering'],
    inductionsOpen: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '11',
    title: 'Film Club',
    type: 'Club',
    description: 'Exploring cinema as an art form through screenings, discussions, and student film productions.',
    fullDescription: 'The Film Club celebrates cinema in all its forms. We screen films from around the world, host discussions on filmmaking techniques and narrative styles, organize film festivals, and support members in creating their own short films. From classic cinema to contemporary indie films, we explore the artistic and cultural significance of moving images.',
    imageUrl: 'https://images.pexels.com/photos/3944454/pexels-photo-3944454.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Film', 'Media', 'Arts'],
    inductionsOpen: false,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '12',
    title: 'Music Society',
    type: 'Society',
    description: 'Creating harmony through diverse musical genres, from classical to contemporary performances.',
    fullDescription: 'The Music Society brings together musicians of all styles and skill levels. We organize jam sessions, provide practice spaces, host concerts featuring student performers, and collaborate on musical productions. Members explore various instruments, vocal techniques, music theory, and performance skills. We also invite guest artists for workshops and masterclasses.',
    imageUrl: 'https://images.pexels.com/photos/3971985/pexels-photo-3971985.jpeg?auto=compress&cs=tinysrgb&w=800',
    categories: ['Music', 'Performing Arts', 'Culture'],
    inductionsOpen: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
];
