import { Asset } from './types';

export const sampleAssets: Asset[] = [
  {
    id: '1',
    name: 'Type C USB Cable',
    description: '1.5 Meters, 50 Grams, Black, 1N Cable, 1N Rating Card',
    tab: 'Techmin',
    type: 'Cable',
    status: 'available',
    imageUrl: 'https://images.pexels.com/photos/4526404/pexels-photo-4526404.jpeg?auto=compress&cs=tinysrgb&w=800',
    bookmarked: true,
  },
  {
    id: '2',
    name: 'Boat Speaker',
    description: 'Portable Bluetooth Speaker with RGB Lights',
    tab: 'Jazbaa',
    type: 'Speaker',
    status: 'available',
    imageUrl: 'https://images.pexels.com/photos/8000616/pexels-photo-8000616.jpeg?auto=compress&cs=tinysrgb&w=800',
    bookmarked: true,
  },
  {
    id: '3',
    name: 'Braided Micro USB Cable',
    description: '1.5 Meters, 52 Grams, Black, 1 N Cable, 1 N Rating Card',
    tab: 'Techmin',
    type: 'Cable',
    status: 'available',
    imageUrl: 'https://images.pexels.com/photos/4526404/pexels-photo-4526404.jpeg?auto=compress&cs=tinysrgb&w=800',
    bookmarked: true,
  },
  {
    id: '4',
    name: 'Type C USB Cable',
    description: '1.5 Meters, 50 Grams, Black, 1N Cable, 1N Rating Card',
    tab: 'Techmin',
    type: 'Cable',
    status: 'available',
    imageUrl: 'https://images.pexels.com/photos/4526404/pexels-photo-4526404.jpeg?auto=compress&cs=tinysrgb&w=800',
    bookmarked: false,
  },
  {
    id: '5',
    name: 'YUVA 3 (Eclipse Black)',
    description: 'Fast UNISOC T606 Processor (AnTuTu 200K+), 4GB+4GB RAM 64GB UFS 2.2 Memory',
    tab: 'Techmin',
    type: 'Phone',
    status: 'unavailable',
    imageUrl: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=800',
    overdueDate: 'Jun 30 2025',
    bookmarked: true,
  },
  {
    id: '6',
    name: 'Type C USB Cable',
    description: '1.5 Meters, 50 Grams, Black, 1N Cable, 1N Rating Card',
    tab: 'Techmin',
    type: 'Cable',
    status: 'unavailable',
    imageUrl: 'https://images.pexels.com/photos/4526404/pexels-photo-4526404.jpeg?auto=compress&cs=tinysrgb&w=800',
    overdueDate: 'Jun 25 2025',
    bookmarked: true,
  },
  {
    id: '7',
    name: 'Fairy Light',
    description: '1.5 Meters, Yellow, with battery',
    tab: 'Jazbaa',
    type: 'Lights',
    status: 'unavailable',
    imageUrl: 'https://images.pexels.com/photos/1363876/pexels-photo-1363876.jpeg?auto=compress&cs=tinysrgb&w=800',
    overdueDate: 'Aug 30 2025',
    bookmarked: true,
  },
  {
    id: '8',
    name: 'Type C USB Cable',
    description: '1.5 Meters, 50 Grams, Black, 1N Cable, 1N Rating Card',
    tab: 'Techmin',
    type: 'Cable',
    status: 'unavailable',
    overdueDate: 'Jun 30 2025',
    bookmarked: false,
  },
  {
    id: '9',
    name: 'Wireless Mouse',
    description: '2.4GHz Wireless, Ergonomic Design, 1600 DPI',
    tab: 'Techmin',
    type: 'Accessories',
    status: 'available',
    bookmarked: false,
  },
  {
    id: '10',
    name: 'HDMI Cable',
    description: '2 Meters, 4K Support, Gold Plated Connectors',
    tab: 'Techmin',
    type: 'Cable',
    status: 'available',
    bookmarked: true,
  },
];
